# -*- coding: utf-8 -*-
"""Tugas 6 KSI_222112154_Substitution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUXWxr6upJxmy4t8Eop-giGQwI_FKjLL

**ENCRYPT**
"""

def encrypt_substitution(text, key):
    # Buat peta penggantian karakter
    char_map = {}
    for i in range(len(key)):
        char_map[chr(97 + i)] = key[i]

    # Enkripsi teks
    encrypted_text = ''.join(char_map.get(char, char) for char in text.lower())
    return encrypted_text

def decrypt_substitution(text, key):
    # Buat peta penggantian karakter
    char_map = {}
    for i in range(len(key)):
        char_map[key[i]] = chr(97 + i)

    # Dekripsi teks
    decrypted_text = ''.join(char_map.get(char, char) for char in text.lower())
    return decrypted_text

def main():
    text = input("Masukkan teks yang ingin dienkripsi: ")
    key = input("Masukkan kunci untuk enkripsi: ")

    # Enkripsi teks
    encrypted_text = encrypt_substitution(text, key)

    # Dekripsi teks
    decrypted_text = decrypt_substitution(encrypted_text, key)

    # Tampilkan hasil
    print("Original text:   ", text)
    print("Encrypted text:", encrypted_text)
    print("Decrypted text:", decrypted_text)

if __name__ == "__main__":
    main()

"""**DECRYPT**"""

def decrypt_substitution(text, key):
    # Buat peta penggantian karakter
    char_map = {}
    for i in range(len(key)):
        char_map[key[i]] = chr(97 + i)

    # Dekripsi teks
    decrypted_text = ''.join(char_map.get(char, char) for char in text.lower())
    return decrypted_text

def main():
    text = input("Masukkan teks yang ingin dienkripsi: ")
    key = input("Masukkan kunci untuk enkripsi: ")

    # Dekripsi teks
    decrypted_text = decrypt_substitution(text, key)

    # Tampilkan hasil
    print("Encrypted text:", text)
    print("Decrypted text:", decrypted_text)

if __name__ == "__main__":
    main()